In [141]:
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

### Any Preprocess

In [142]:
(train_data, train_labels), (test_data, test_labels) = tf.keras.datasets.boston_housing.load_data()

In [143]:
train_data.shape

(404, 13)

In [144]:
train_data[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [145]:
train_data[1]

array([2.1770e-02, 8.2500e+01, 2.0300e+00, 0.0000e+00, 4.1500e-01,
       7.6100e+00, 1.5700e+01, 6.2700e+00, 2.0000e+00, 3.4800e+02,
       1.4700e+01, 3.9538e+02, 3.1100e+00])

In [146]:
train_data[2]

array([4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
       4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
       2.02000e+01, 3.75520e+02, 3.26000e+00])

In [147]:
train_labels.shape

(404,)

In [148]:
test_data.shape, test_labels.shape

((102, 13), (102,))

In [149]:
train_data.dtype

dtype('float64')

In [150]:
train_data.min(axis=0)

array([6.3200e-03, 0.0000e+00, 4.6000e-01, 0.0000e+00, 3.8500e-01,
       3.5610e+00, 2.9000e+00, 1.1296e+00, 1.0000e+00, 1.8800e+02,
       1.2600e+01, 3.2000e-01, 1.7300e+00])

In [151]:
train_data.max(axis=0)

array([ 88.9762, 100.    ,  27.74  ,   1.    ,   0.871 ,   8.725 ,
       100.    ,  10.7103,  24.    , 711.    ,  22.    , 396.9   ,
        37.97  ])

In [152]:
train_labels.max()

np.float64(50.0)

In [153]:
## Normalize between 0 , 1
## Dtype = float32
## Compatible shape

In [154]:
min_max_scaler = MinMaxScaler()

In [155]:
min_max_scaler.fit(train_data)

MinMaxScaler()

In [156]:
train_data = min_max_scaler.transform(train_data)

In [157]:
train_data.min(axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [158]:
train_data.max(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [159]:
test_data = min_max_scaler.transform(test_data)

In [160]:
test_data.min(axis=0)

array([ 7.63179629e-05,  0.00000000e+00,  2.78592375e-02,  0.00000000e+00,
        1.44032922e-02,  2.55422153e-01,  3.19258496e-02,  3.50600687e-02,
        0.00000000e+00, -1.91204589e-03,  4.25531915e-02,  6.13495386e-02,
        5.24282561e-03])

In [161]:
test_data.max(axis=0)

array([0.28144109, 0.9       , 1.        , 1.        , 1.        ,
       1.01065066, 1.        , 1.14781801, 1.        , 1.        ,
       0.91489362, 1.        , 0.83498896])

In [162]:
train_data.dtype

dtype('float64')

In [163]:
train_data = train_data.astype(np.float32)
test_data = test_data.astype(np.float32)

In [164]:
train_data.dtype, test_data.dtype

(dtype('float32'), dtype('float32'))

In [165]:
train_labels.min()

np.float64(5.0)

In [166]:
train_labels.max()

np.float64(50.0)

In [167]:
train_labels = train_labels.astype(np.float32).reshape((-1, 1)) / 50.

In [168]:
train_labels.dtype

dtype('float32')

In [169]:
train_labels.shape

(404, 1)

In [170]:
train_labels.max()

np.float32(1.0)

In [171]:
train_labels.min()

np.float32(0.1)

In [172]:
test_labels = test_labels.astype(np.float32).reshape((-1, 1)) / 50.

In [173]:
test_labels.shape

(102, 1)

In [174]:
test_labels.dtype

dtype('float32')

In [175]:
test_labels.max()

np.float32(1.0)

In [176]:
test_labels.min()

np.float32(0.111999996)

## Last final check

In [177]:
## shape
## normalize
## dtype

In [178]:
train_data.shape, train_data.dtype, train_data.min(), train_data.max()

((404, 13), dtype('float32'), np.float32(0.0), np.float32(1.0))

In [179]:
test_data.shape, test_data.dtype, test_data.min(), test_data.max()

((102, 13), dtype('float32'), np.float32(-0.0019120459), np.float32(1.147818))

In [180]:
train_labels.shape, train_labels.dtype, train_labels.min(), train_labels.max()

((404, 1), dtype('float32'), np.float32(0.1), np.float32(1.0))

In [181]:
test_labels.shape, test_labels.dtype, test_labels.min(), test_labels.max()

((102, 1), dtype('float32'), np.float32(0.111999996), np.float32(1.0))

In [182]:
train_batch = train_data[:16]
train_batch.shape

(16, 13)

In [183]:
label_batch = train_labels[0:16]
label_batch.shape

(16, 1)

## Create our first regression model

In [184]:
# from tensorflow.keras.models import Model, Sequential
# from tensorflow.keras.layers import Input, Dense

In [185]:
seq_model = tf.keras.models.Sequential()

In [186]:
input_layer = tf.keras.layers.Input((13, ), batch_size=16)

first_layer_output = tf.keras.layers.Dense(units=13, activation=tf.nn.relu, use_bias=False)(input_layer)
second_layer_output = tf.keras.layers.Dense(units=8, activation="relu", use_bias=False)(first_layer_output)
predictions = tf.keras.layers.Dense(units=1)(second_layer_output)

regression_model = tf.keras.models.Model(input_layer, predictions)

In [187]:
regression_model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (16, 13)               │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (16, 13)               │           169 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (16, 8)                │           104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (16, 1)                │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 282 (1.10 KB)

 Trainable params: 282 (1.10 KB)

 Non-trainable params: 0 (0.00 B)