In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

2025-02-13 12:02:22.091777: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-13 12:02:22.092950: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-13 12:02:22.097203: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-13 12:02:22.110220: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739435542.131803    6419 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739435542.13

### Any Preprocess

In [2]:
(train_data, train_labels), (_, _) = tf.keras.datasets.boston_housing.load_data()

In [3]:
train_data.shape

(404, 13)

In [4]:
train_data[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [5]:
train_data[1]

array([2.1770e-02, 8.2500e+01, 2.0300e+00, 0.0000e+00, 4.1500e-01,
       7.6100e+00, 1.5700e+01, 6.2700e+00, 2.0000e+00, 3.4800e+02,
       1.4700e+01, 3.9538e+02, 3.1100e+00])

In [6]:
train_data[2]

array([4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
       4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
       2.02000e+01, 3.75520e+02, 3.26000e+00])

In [7]:
train_labels.shape

(404,)

In [8]:
test_data.shape, test_labels.shape

NameError: name 'test_data' is not defined

In [ ]:
train_data.dtype

In [ ]:
train_data.min(axis=0)

In [ ]:
train_data.max(axis=0)

In [ ]:
train_label.max()

In [ ]:
## Normalize between 0 , 1
## Dtype = float32
## Compatible shape

In [ ]:
min_max_scaler = MinMaxScaler()

In [ ]:
min_max_scaler.fit(train_data)

In [ ]:
train_data = min_max_scaler.transform(train_data)

In [ ]:
train_data.min(axis=0)

In [ ]:
train_data.max(axis=0)

In [ ]:
test_data = min_max_scaler.transform(test_data)

In [ ]:
test_data.min(axis=0)

In [ ]:
test_data.max(axis=0)

In [ ]:
train_data.dtype

In [ ]:
train_data = train_data.astype(np.float32)
test_data = test_data.astype(np.float32)

In [ ]:
train_data.dtype, test_data.dtype

In [ ]:
train_labels.min()

In [ ]:
train_labels.max()

In [ ]:
train_labels = train_labels.astype(np.float32).reshape((-1, 1)) / 50.

In [ ]:
train_labels.dtype

In [ ]:
train_labels.shape

In [ ]:
train_labels.max()

In [ ]:
train_labels.min()

In [ ]:
test_labels = test_labels.astype(np.float32).reshape((-1, 1)) / 50.

In [ ]:
test_labels.shape

In [ ]:
test_labels.dtype

In [ ]:
test_labels.max()

In [ ]:
test_labels.min()

## Last final check

In [ ]:
## shape
## normalize
## dtype

In [ ]:
train_data.shape, train_data.dtype, train_data.min(), train_data.max()

In [ ]:
test_data.shape, test_data.dtype, test_data.min(), test_data.max()

In [ ]:
train_labels.shape, train_labels.dtype, train_labels.min(), train_labels.max()

In [ ]:
test_labels.shape, test_labels.dtype, test_labels.min(), test_labels.max()

In [ ]:
train_batch = train_data[:16]
train_batch.shape

In [ ]:
label_batch = train_labels[0:16]
label_batch.shape

## Create our first regression model

In [ ]:
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, Dense

In [ ]:
seq_model = Sequential()

In [ ]:
input_layer = Input((13, ), batch_size=16)

first_layer_output = Dense(units=13, activation=tf.nn.relu, use_bias=False)(input_layer)
second_layer_output = Dense(units=8, activation="relu", use_bias=False)(first_layer_output)
predictions = Dense(units=1)(second_layer_output)

regression_model = Model(input_layer, predictions)

In [ ]:
regression_model.summary()