In [ ]:
import numpy as np

In [1]:
import tensorflow as tf

2025-02-13 17:22:33.718061: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-13 17:22:33.718606: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-13 17:22:33.721431: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-13 17:22:33.729663: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739454753.744494   63811 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739454753.74

In [2]:
l1 = [1, 2 , 3]

In [3]:
l1

[1, 2, 3]

In [4]:
print(l1)

[1, 2, 3]


In [5]:
print(l1+l1)

[1, 2, 3, 1, 2, 3]


In [6]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [7]:
print("Hello World!")

Hello World!


b = True

In [8]:
b = 1.1

In [9]:
b, type(b)

(1.1, float)

In [10]:
print(type(b))

<class 'float'>


In [11]:
i = 2

In [12]:
i, type(i)

(2, int)

In [13]:
f = 2.0

In [14]:
f, type(f)

(2.0, float)

In [15]:
c = 1 + 3j

In [16]:
c, type(c)

((1+3j), complex)

In [17]:
s1 = 'mamad'

In [18]:
s1

'mamad'

In [19]:
s2 = 'mamad rafte "folanja"'

In [20]:
s2, s2

('mamad rafte "folanja"', 'mamad rafte "folanja"')

In [21]:
s1 = "abc"

In [22]:
s2 = "123"

In [23]:
print(s1)

abc


In [24]:
print(s2)

123


In [25]:
print(s1+s2)

abc123


In [26]:
s2.index("3")

2

In [27]:
s2.endswith("3")

True

In [28]:
"3" in s2

True

In [29]:
s2.find("3")

2

In [30]:
my_list = [1, 2, 3, 4.1, "mamad", "part", ["hassan", 3.3]]

In [31]:
my_list

[1, 2, 3, 4.1, 'mamad', 'part', ['hassan', 3.3]]

In [32]:
for item in my_list:
    print(type(item))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'list'>


In [33]:
type(my_list)

list

In [34]:
len(my_list)

7

In [35]:
my_list.index("mamad")

4

In [36]:
my_list.append("mamad2")

In [37]:
my_list[-1]

'mamad2'

In [38]:
test_list = ["extend1", "extend2"]

In [39]:
my_list.append(test_list)

In [40]:
my_list.extend(my_list)

In [41]:
my_list = [1, 2, 3, 4.1, "mamad", "part", ["hassan", 3.3]]

In [42]:
my_list + test_list

[1, 2, 3, 4.1, 'mamad', 'part', ['hassan', 3.3], 'extend1', 'extend2']

In [43]:
my_list.append(test_list)

In [44]:
my_list

[1, 2, 3, 4.1, 'mamad', 'part', ['hassan', 3.3], ['extend1', 'extend2']]

In [45]:
my_list.extend(test_list)

In [46]:
my_list

[1,
 2,
 3,
 4.1,
 'mamad',
 'part',
 ['hassan', 3.3],
 ['extend1', 'extend2'],
 'extend1',
 'extend2']

In [47]:
my_list.insert(2, 2.5)

In [48]:
my_list

[1,
 2,
 2.5,
 3,
 4.1,
 'mamad',
 'part',
 ['hassan', 3.3],
 ['extend1', 'extend2'],
 'extend1',
 'extend2']

In [49]:
my_list.insert(-1, 3.5)

In [50]:
my_list, my_list

([1,
  2,
  2.5,
  3,
  4.1,
  'mamad',
  'part',
  ['hassan', 3.3],
  ['extend1', 'extend2'],
  'extend1',
  3.5,
  'extend2'],
 [1,
  2,
  2.5,
  3,
  4.1,
  'mamad',
  'part',
  ['hassan', 3.3],
  ['extend1', 'extend2'],
  'extend1',
  3.5,
  'extend2'])

In [51]:
my_list.remove(3.5)

In [52]:
my_list

[1,
 2,
 2.5,
 3,
 4.1,
 'mamad',
 'part',
 ['hassan', 3.3],
 ['extend1', 'extend2'],
 'extend1',
 'extend2']

In [53]:
my_list.pop()

'extend2'

In [54]:
my_list

[1,
 2,
 2.5,
 3,
 4.1,
 'mamad',
 'part',
 ['hassan', 3.3],
 ['extend1', 'extend2'],
 'extend1']

In [55]:
my_list.pop(1)

2

In [56]:
my_list

[1,
 2.5,
 3,
 4.1,
 'mamad',
 'part',
 ['hassan', 3.3],
 ['extend1', 'extend2'],
 'extend1']

In [57]:
my_list.pop(1)

2.5

In [58]:
my_list

[1,
 3,
 4.1,
 'mamad',
 'part',
 ['hassan', 3.3],
 ['extend1', 'extend2'],
 'extend1']

In [59]:
for item in my_list:
    if not item == False:
        print(item)

1
3
4.1
mamad
part
['hassan', 3.3]
['extend1', 'extend2']
extend1


In [60]:
sub_list = my_list[0:3]

In [61]:
sub_list

[1, 3, 4.1]

In [62]:
sub_list = my_list[2:]

In [63]:
sub_list

[4.1, 'mamad', 'part', ['hassan', 3.3], ['extend1', 'extend2'], 'extend1']

In [64]:
sub_list = my_list[1::2]

In [65]:
sub_list

[3, 'mamad', ['hassan', 3.3], 'extend1']

In [66]:
sub_list = my_list[1::1]

In [67]:
sub_list

[3, 4.1, 'mamad', 'part', ['hassan', 3.3], ['extend1', 'extend2'], 'extend1']

In [68]:
my_list_copy = my_list.copy()


In [69]:
my_list_copy[1]

3

In [70]:
my_list_copy[1] = 200

In [71]:
my_list

[1,
 3,
 4.1,
 'mamad',
 'part',
 ['hassan', 3.3],
 ['extend1', 'extend2'],
 'extend1']

In [72]:
my_list_copy

[1,
 200,
 4.1,
 'mamad',
 'part',
 ['hassan', 3.3],
 ['extend1', 'extend2'],
 'extend1']

In [73]:
tpl = (50, 1)

In [74]:
tpl, type(tpl)

((50, 1), tuple)

In [75]:
my_tp = ("a", "b", "c")

In [76]:
my_tp

('a', 'b', 'c')

In [77]:
my_tp_list = list(my_tp)

In [78]:
my_tp_list[1] = "change"

In [79]:
my_tp_list

['a', 'change', 'c']

In [80]:
my_tp

('a', 'b', 'c')

In [81]:
my_tp_list[:-2]

['a']

In [82]:
# comment

In [83]:
my_dict = {"key1": 23, "key2": 48, "key3" : 12, 12: 112}

In [84]:
my_dict

{'key1': 23, 'key2': 48, 'key3': 12, 12: 112}

In [85]:
my_dict[12]

112

In [86]:
my_dict["key2"] = 12

In [87]:
my_dict

{'key1': 23, 'key2': 12, 'key3': 12, 12: 112}

In [88]:
my_dict["key4"] = "test"

In [89]:
my_dict

{'key1': 23, 'key2': 12, 'key3': 12, 12: 112, 'key4': 'test'}

In [90]:
np_arr = np.array([1, 2, 3, 4, 5.5])

NameError: name 'np' is not defined

In [ ]:
np_arr

array([1. , 2. , 3. , 4. , 5.5])

In [ ]:
array = [1, 2, 3]

In [ ]:
array

[1, 2, 3]

In [ ]:
empty_arr = np.array([])

In [ ]:
empty_arr

array([], dtype=float64)

In [ ]:
empty_arr.shape

(0,)

In [ ]:
empty_arr.strides

(0,)

In [ ]:
np_arr.shape

(5,)

In [ ]:
np_arr.dtype

dtype('float64')

In [ ]:
np_arr.size

5

In [ ]:
np_arr.ndim

1

In [ ]:
np_arr.strides

(8,)

In [ ]:
np_arr2 = np.array([1, 2, 3, 4, 5])

In [ ]:
np_arr2.strides

(8,)

In [ ]:
np_arr3 = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
np_arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_arr3.strides

(24, 8)

In [ ]:
np.size

<function size at 0x7f04e851c830>

In [ ]:
np_arr3.size

6

In [ ]:
np_arr3.ndim

2

In [ ]:
np_arr = np.arange(10) + 1.

In [ ]:
np_arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np_z = np.zeros((3, 4), dtype = np.float32)

In [ ]:
np_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [ ]:
np_o = np.ones((4, 3))

In [ ]:
np_o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np_arr = np.linspace(2, 30, 50)

In [ ]:
np_arr

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ,
       10.57142857, 11.14285714, 11.71428571, 12.28571429, 12.85714286,
       13.42857143, 14.        , 14.57142857, 15.14285714, 15.71428571,
       16.28571429, 16.85714286, 17.42857143, 18.        , 18.57142857,
       19.14285714, 19.71428571, 20.28571429, 20.85714286, 21.42857143,
       22.        , 22.57142857, 23.14285714, 23.71428571, 24.28571429,
       24.85714286, 25.42857143, 26.        , 26.57142857, 27.14285714,
       27.71428571, 28.28571429, 28.85714286, 29.42857143, 30.        ])

In [ ]:
np.linspace(2, 30, 29)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
       28., 29., 30.])

In [ ]:
rand_arr2 = np.random.uniform(low=10.0, high=50.0, size=(3, 4))

In [ ]:
rand_arr2

array([[41.98716192, 46.83000925, 27.01753115, 13.49329552],
       [31.61639448, 23.0028233 , 24.31829771, 11.10130834],
       [20.51230466, 37.92889018, 25.97537205, 31.22015824]])

In [ ]:
rand_arr = np.random.rand(3, 4)

In [ ]:
rand_arr

array([[0.06319811, 0.35714246, 0.59380148, 0.97718289],
       [0.72614551, 0.91309938, 0.58417297, 0.63661025],
       [0.99902837, 0.87209554, 0.26216684, 0.35218724]])

In [ ]:
rand_arr.dtype

dtype('float64')

In [ ]:
rand_arr = rand_arr.astype(np.float32)

In [ ]:
rand_arr.dtype

dtype('float32')

In [ ]:
reshape_arr = np.reshape(rand_arr, newshape=(6, -1))

In [ ]:
reshape_arr

array([[0.06319811, 0.35714245],
       [0.5938015 , 0.97718287],
       [0.7261455 , 0.91309935],
       [0.58417296, 0.63661027],
       [0.9990284 , 0.8720955 ],
       [0.26216683, 0.35218725]], dtype=float32)

In [ ]:
reshape_arr.max()

np.float32(0.9990284)

In [ ]:
np.median(reshape_arr)

np.float32(0.6152059)

In [ ]:
np.argmax(reshape_arr)

np.int64(8)

In [ ]:
np.min(reshape_arr, axis=0)

array([0.06319811, 0.35218725], dtype=float32)

In [ ]:
np.random.seed(124)

In [ ]:
np_arr = np.random.rand(10, 6)

In [ ]:
np_arr

array([[0.10606491, 0.74547148, 0.57231354, 0.45824118, 0.3847059 ,
        0.27398931],
       [0.66796241, 0.39547501, 0.28157289, 0.77991971, 0.59909416,
        0.12294636],
       [0.38957403, 0.97498836, 0.4675989 , 0.14017141, 0.04206858,
        0.72799627],
       [0.61560551, 0.9027321 , 0.62263341, 0.2601217 , 0.55551768,
        0.40498648],
       [0.14175587, 0.57774636, 0.52652124, 0.93856912, 0.95887879,
        0.9844318 ],
       [0.23095612, 0.09707925, 0.24574867, 0.69075766, 0.1974319 ,
        0.8295272 ],
       [0.34612727, 0.51401486, 0.66115798, 0.93362449, 0.06690067,
        0.74688969],
       [0.39028262, 0.53575843, 0.06042919, 0.8913558 , 0.77787374,
        0.6701197 ],
       [0.7350527 , 0.66369952, 0.18176625, 0.86299757, 0.45142896,
        0.6497297 ],
       [0.15937201, 0.40598175, 0.79885158, 0.72915428, 0.07090418,
        0.76971324]])

In [ ]:
sub_arr = np_arr[2:5, :3]

In [ ]:
np_arr.size

60

In [ ]:
np_arr.ndim

2

In [ ]:
sub_arr

array([[0.38957403, 0.97498836, 0.4675989 ],
       [0.61560551, 0.9027321 , 0.62263341],
       [0.14175587, 0.57774636, 0.52652124]])

In [ ]:
# cropped_image = image[20:-20, 30:-30, :]

In [ ]:
np.random.seed(56)

In [ ]:
np_arr = np.random.rand(12)

In [ ]:
np_arr

array([0.98419185, 0.33341227, 0.67370162, 0.19639042, 0.35444646,
       0.81336595, 0.24784955, 0.45861133, 0.87730142, 0.39165846,
       0.32613342, 0.09009511])

In [ ]:
mask = np_arr > 0.5

In [ ]:
mask

array([ True, False,  True, False, False,  True, False, False,  True,
       False, False, False])

In [ ]:
np_cond_arr = np_arr[mask]

In [ ]:
np_cond_arr

array([0.98419185, 0.67370162, 0.81336595, 0.87730142])

In [ ]:
np_cond_arr2 = np_arr[np_arr > 0.5]

In [ ]:
np_cond_arr2

array([0.98419185, 0.67370162, 0.81336595, 0.87730142])

In [ ]:
np_cond_arr = np_cond_arr / 2.

In [ ]:
np_cond_arr

array([0.49209593, 0.33685081, 0.40668298, 0.43865071])

In [ ]:
np.random.seed(57)

In [ ]:
test_array = np_cond_arr2 + np.random.rand(np_cond_arr2.shape[0])

In [ ]:
test_array

array([1.07154149, 0.90417872, 1.22442702, 1.18808412])

In [ ]:
np.random.seed(124)

In [ ]:
np_arr = np.random.rand(10, 6)

In [ ]:
np_arr

array([[0.10606491, 0.74547148, 0.57231354, 0.45824118, 0.3847059 ,
        0.27398931],
       [0.66796241, 0.39547501, 0.28157289, 0.77991971, 0.59909416,
        0.12294636],
       [0.38957403, 0.97498836, 0.4675989 , 0.14017141, 0.04206858,
        0.72799627],
       [0.61560551, 0.9027321 , 0.62263341, 0.2601217 , 0.55551768,
        0.40498648],
       [0.14175587, 0.57774636, 0.52652124, 0.93856912, 0.95887879,
        0.9844318 ],
       [0.23095612, 0.09707925, 0.24574867, 0.69075766, 0.1974319 ,
        0.8295272 ],
       [0.34612727, 0.51401486, 0.66115798, 0.93362449, 0.06690067,
        0.74688969],
       [0.39028262, 0.53575843, 0.06042919, 0.8913558 , 0.77787374,
        0.6701197 ],
       [0.7350527 , 0.66369952, 0.18176625, 0.86299757, 0.45142896,
        0.6497297 ],
       [0.15937201, 0.40598175, 0.79885158, 0.72915428, 0.07090418,
        0.76971324]])

In [ ]:
np.sum(np_arr, axis=1)

array([2.54078632, 2.84697054, 2.74239755, 3.36159688, 4.12790319,
       2.2915008 , 3.26871495, 3.32581947, 3.5446747 , 2.93397704])

In [ ]:
arr1 = np.random.rand(2, 3, 10)

In [ ]:
arr2 = np.random.rand(2, 3 ,5)

In [ ]:
cc_arr = np.concatenate((arr1, arr2), axis=2)

In [ ]:
arr1

array([[[0.4972157 , 0.76692173, 0.67975852, 0.13026067, 0.65874366,
         0.24532891, 0.24545168, 0.83795581, 0.10549054, 0.72643234],
        [0.94568558, 0.72166491, 0.14389831, 0.79305307, 0.70895346,
         0.97247011, 0.97751567, 0.49999879, 0.65569244, 0.26876842],
        [0.63248955, 0.85201293, 0.5689624 , 0.0233863 , 0.55464636,
         0.36860029, 0.96031142, 0.39123483, 0.0380728 , 0.89212374]],

       [[0.14387614, 0.63858675, 0.10003748, 0.89066349, 0.06681054,
         0.74586419, 0.45452347, 0.54724605, 0.6496482 , 0.78183562],
        [0.6608355 , 0.77711325, 0.24588614, 0.01345676, 0.355845  ,
         0.80388206, 0.02799326, 0.73677205, 0.52755007, 0.90523246],
        [0.54311023, 0.53678048, 0.4131242 , 0.77523379, 0.10966945,
         0.13664648, 0.78287393, 0.9083969 , 0.52475929, 0.7493595 ]]])

In [ ]:
arr2

array([[[0.19275227, 0.00719085, 0.60879808, 0.34413601, 0.46909886],
        [0.41924856, 0.70729132, 0.19932869, 0.53038474, 0.65138402],
        [0.06686331, 0.97179318, 0.65702222, 0.11786682, 0.31540731]],

       [[0.88923013, 0.55640871, 0.91047823, 0.28466641, 0.09346681],
        [0.88953067, 0.99193383, 0.18322521, 0.81854553, 0.56639097],
        [0.014208  , 0.29673064, 0.6347744 , 0.6801958 , 0.39601146]]])

In [ ]:
cc_arr

array([[[0.4972157 , 0.76692173, 0.67975852, 0.13026067, 0.65874366,
         0.24532891, 0.24545168, 0.83795581, 0.10549054, 0.72643234,
         0.19275227, 0.00719085, 0.60879808, 0.34413601, 0.46909886],
        [0.94568558, 0.72166491, 0.14389831, 0.79305307, 0.70895346,
         0.97247011, 0.97751567, 0.49999879, 0.65569244, 0.26876842,
         0.41924856, 0.70729132, 0.19932869, 0.53038474, 0.65138402],
        [0.63248955, 0.85201293, 0.5689624 , 0.0233863 , 0.55464636,
         0.36860029, 0.96031142, 0.39123483, 0.0380728 , 0.89212374,
         0.06686331, 0.97179318, 0.65702222, 0.11786682, 0.31540731]],

       [[0.14387614, 0.63858675, 0.10003748, 0.89066349, 0.06681054,
         0.74586419, 0.45452347, 0.54724605, 0.6496482 , 0.78183562,
         0.88923013, 0.55640871, 0.91047823, 0.28466641, 0.09346681],
        [0.6608355 , 0.77711325, 0.24588614, 0.01345676, 0.355845  ,
         0.80388206, 0.02799326, 0.73677205, 0.52755007, 0.90523246,
         0.88953067, 0.99193

In [ ]:
np.random.seed(49)

In [ ]:
arr = np.random.rand(16)

In [ ]:
for i, e in enumerate(arr):
    if e > 0.5:
        print(e)
    elif e < 0.4:
        print("low element = {} on index = {}".format(e, i))

low element = 0.3009644558559146 on index = 0
low element = 0.24706183196181442 on index = 1
0.9263351350591756
0.891603438277764
0.6832767599749869
0.5668846594996723
0.5469658802430317
low element = 0.21042383598676584 on index = 7
0.7697544681854357
0.8962301009569733
0.7216504565659716
0.8024305278044254
0.8448313057399196
low element = 0.22913820441272792 on index = 15


In [ ]:
def my_func(value1, value2=0):
    print("value = {} and {}".format(value1, value2))
    return value1 + "_test", value2 + 1

In [ ]:
my_func("mamad")

value = mamad and 0


('mamad_test', 1)

In [ ]:
class MyClass:

    def __init__(self, arg1, arg2):
        self.arg1 = arg1
        self.arg2 = arg2

    def mtd(self):
        print(self.arg1)
        print(self.arg2)

    def area(self):
        raise NotImplementedError("Subclasses must implement this method")

In [ ]:
mc = MyClass("mamad", 24)

In [ ]:
mc

In [ ]:
mc.mtd()

mamad
24


In [ ]:
class Shape:
    def __init__(self, color):

        # Storing the color of the shape
        self.color = color

    def area(self):

        # This method should be implemented by subclasses
        raise NotImplementedError("Subclasses must implement this method")

class Circle(Shape):
    def __init__(self, color, radius):

        # Initialize the parent class (Shape) with color
        super().__init__(color)

        # Storing the radius of the circle
        self.radius = radius

    def area(self):

        # Circle-specific area calculation
        return 3.14 * self.radius ** 2

# Creating instances
# Shape instance with color 'Red'
s = Shape("Red")

# Circle instance with color 'Blue' and radius 5
c = Circle("Blue", 5)

# Accessing attributes and methods
print(s.color)  # Output: Red
print(c.color)  # Output: Blue
print(c.radius)  # Output: 5
print(c.area())  # Output: 78.5

Red
Blue
5
78.5


In [ ]:
class MyClass:

    def __init__(self, arg1, arg2):
        self.arg1 = arg1
        self.arg2 = arg2

    def mtd(self):
        print(self.arg1)
        print(self.arg2)

    def area(self):
        raise NotImplementedError("Subclasses must implement this method")

class MySubClass(MyClass):
    def __init__(self, arg1, arg2, arg3):


        super().__init__(arg1, arg2)

        self.arg3 = arg3

    def area(self):
        return self.arg1 + self.arg2 + self.arg3

msc = MySubClass(1, 2, 3)
msc.area()

6

In [ ]:
import os

In [ ]:
import pickle

In [ ]:
os.listdir("/")

['lost+found',
 'etc',
 'root',
 'mnt',
 'tmp',
 'bin',
 'sys',
 'media',
 'init',
 'lib.usr-is-merged',
 'var',
 'sbin.usr-is-merged',
 'home',
 'srv',
 'snap',
 'sbin',
 'lib64',
 'dev',
 'boot',
 'proc',
 'bin.usr-is-merged',
 'run',
 'opt',
 'usr',
 'lib']

In [ ]:
for file_name in os.listdir("./"):
    if "numpy" in file_name:
        print(file_name)

In [ ]:
if not os.path.exists("testdir/"):
    os.mkdir("testdir/")
else:
    print("exists")

exists


In [ ]:
os.listdir("./")

['test_dir',
 'test_file.txt',
 'my_first_pickle.pkl',
 'testdir',
 'workspace.code-workspace']

In [ ]:
test_dict = {"k1": 1, "k2": 2, "k3": 3}

In [ ]:
pickle.dump(test_dict, open("my_first_pickle.pkl", "wb"))

In [ ]:
loaded_dict = pickle.load(open("my_first_pickle.pkl", "rb"))

In [ ]:
loaded_dict

{'k1': 1, 'k2': 2, 'k3': 3}

In [ ]:
test_dict

{'k1': 1, 'k2': 2, 'k3': 3}

In [ ]:
import tensorflow as tf

In [ ]:
tensor_array = tf.convert_to_tensor([[1, 2], [4, 5]])

W0000 00:00:1739454643.710874   63440 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [ ]:
tensor_array

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
type(tensor_array)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
tensor_array.shape

TensorShape([2, 2])

In [ ]:
tensor_array.dtype

tf.int32

In [ ]:
int_tensor_array = tf.cast(tensor_array, dtype=tf.int32)

In [ ]:
int_tensor_array

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
tf_z = tf.zeros((3, 4), dtype=tf.float32)

In [ ]:
tf_z

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.random.set_seed(46)
rand_tf = tf.random.uniform(shape=(4, 10), maxval=1., dtype=tf.float32)

In [ ]:
rand_tf

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.7300668 , 0.25103962, 0.42991805, 0.11459172, 0.4995339 ,
        0.39785516, 0.717703  , 0.8796133 , 0.41742086, 0.8905815 ],
       [0.04490781, 0.64715993, 0.6124575 , 0.8963598 , 0.50094795,
        0.5403452 , 0.13583767, 0.796286  , 0.11443329, 0.6610137 ],
       [0.75864327, 0.05791759, 0.9041784 , 0.5926819 , 0.14621067,
        0.10904384, 0.28547847, 0.65069926, 0.09890389, 0.7398746 ],
       [0.56936777, 0.7675011 , 0.27471685, 0.72731483, 0.69775176,
        0.50558805, 0.98601305, 0.7327801 , 0.85814536, 0.04894578]],
      dtype=float32)>

In [ ]:
tf_reshape = tf.reshape(rand_tf, (5, 8))

In [ ]:
tf_reshape

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0.7300668 , 0.25103962, 0.42991805, 0.11459172, 0.4995339 ,
        0.39785516, 0.717703  , 0.8796133 ],
       [0.41742086, 0.8905815 , 0.04490781, 0.64715993, 0.6124575 ,
        0.8963598 , 0.50094795, 0.5403452 ],
       [0.13583767, 0.796286  , 0.11443329, 0.6610137 , 0.75864327,
        0.05791759, 0.9041784 , 0.5926819 ],
       [0.14621067, 0.10904384, 0.28547847, 0.65069926, 0.09890389,
        0.7398746 , 0.56936777, 0.7675011 ],
       [0.27471685, 0.72731483, 0.69775176, 0.50558805, 0.98601305,
        0.7327801 , 0.85814536, 0.04894578]], dtype=float32)>

In [ ]:
tf.reduce_min(tf_reshape)

<tf.Tensor: shape=(), dtype=float32, numpy=0.04490780830383301>

In [ ]:
tf_reshape

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0.7300668 , 0.25103962, 0.42991805, 0.11459172, 0.4995339 ,
        0.39785516, 0.717703  , 0.8796133 ],
       [0.41742086, 0.8905815 , 0.04490781, 0.64715993, 0.6124575 ,
        0.8963598 , 0.50094795, 0.5403452 ],
       [0.13583767, 0.796286  , 0.11443329, 0.6610137 , 0.75864327,
        0.05791759, 0.9041784 , 0.5926819 ],
       [0.14621067, 0.10904384, 0.28547847, 0.65069926, 0.09890389,
        0.7398746 , 0.56936777, 0.7675011 ],
       [0.27471685, 0.72731483, 0.69775176, 0.50558805, 0.98601305,
        0.7327801 , 0.85814536, 0.04894578]], dtype=float32)>

In [ ]:
tf.reduce_mean(tf_reshape)

<tf.Tensor: shape=(), dtype=float32, numpy=0.5197457075119019>

In [ ]:
tf.reduce_mean(tf_reshape, axis=0)

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([0.34085056, 0.55485314, 0.3144979 , 0.51581055, 0.59111035,
       0.56495744, 0.7100685 , 0.5658175 ], dtype=float32)>

In [ ]:
sub_tensor = tf_reshape[1:4, 4:7]

In [ ]:
sub_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6124575 , 0.8963598 , 0.50094795],
       [0.75864327, 0.05791759, 0.9041784 ],
       [0.09890389, 0.7398746 , 0.56936777]], dtype=float32)>

In [ ]:
mask = tf_reshape > 0.5

In [ ]:
mask

<tf.Tensor: shape=(5, 8), dtype=bool, numpy=
array([[ True, False, False, False, False, False,  True,  True],
       [False,  True, False,  True,  True,  True,  True,  True],
       [False,  True, False,  True,  True, False,  True,  True],
       [False, False, False,  True, False,  True,  True,  True],
       [False,  True,  True,  True,  True,  True,  True, False]])>

In [ ]:
tf_select = tf_reshape[mask]

In [ ]:
tf_select

<tf.Tensor: shape=(24,), dtype=float32, numpy=
array([0.7300668 , 0.717703  , 0.8796133 , 0.8905815 , 0.64715993,
       0.6124575 , 0.8963598 , 0.50094795, 0.5403452 , 0.796286  ,
       0.6610137 , 0.75864327, 0.9041784 , 0.5926819 , 0.65069926,
       0.7398746 , 0.56936777, 0.7675011 , 0.72731483, 0.69775176,
       0.50558805, 0.98601305, 0.7327801 , 0.85814536], dtype=float32)>

In [ ]:
tf.gather(tf_select, 1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.7177029848098755>

In [ ]:
tf.gather(tf_reshape, (0, 1, 2))

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[0.7300668 , 0.25103962, 0.42991805, 0.11459172, 0.4995339 ,
        0.39785516, 0.717703  , 0.8796133 ],
       [0.41742086, 0.8905815 , 0.04490781, 0.64715993, 0.6124575 ,
        0.8963598 , 0.50094795, 0.5403452 ],
       [0.13583767, 0.796286  , 0.11443329, 0.6610137 , 0.75864327,
        0.05791759, 0.9041784 , 0.5926819 ]], dtype=float32)>

In [ ]:
names = ["ali", "mamad", "mohsen"]

In [ ]:
with open("test_file.txt", "w") as text_file:
    for name in names:
        text_file.write("Name of person = {}\n".format(name))
text_file.close()

In [ ]:
read_names = []
with open("test_file.txt", "r") as text_file:
    lines = text_file.readlines()
    print("this is lines: {}\n".format(lines))
    for index, line in enumerate(lines):
        print("line {}: {}".format(index, line))
        words = line.split(" ")
        print("this is words: {}\n".format(words))
        read_names.append(words[-1][:-1])
        print("this is read names: {}\n".format(read_names))

this is lines: ['Name of person = ali\n', 'Name of person = mamad\n', 'Name of person = mohsen\n']

line 0: Name of person = ali

this is words: ['Name', 'of', 'person', '=', 'ali\n']

this is read names: ['ali']

line 1: Name of person = mamad

this is words: ['Name', 'of', 'person', '=', 'mamad\n']

this is read names: ['ali', 'mamad']

line 2: Name of person = mohsen

this is words: ['Name', 'of', 'person', '=', 'mohsen\n']

this is read names: ['ali', 'mamad', 'mohsen']



In [ ]:
read_names

['ali', 'mamad', 'mohsen']

In [ ]:
(train_data, train_labels), (test_data, test_labels) = tf.keras.datasets.mnist.load_data()

ImportError: cannot import name 'clip_to_image_size' from 'keras.src.layers.preprocessing.image_preprocessing.bounding_boxes.converters' (/home/saeed/anaconda3/envs/ml/lib/python3.9/site-packages/keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/converters.py)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(train_data[0])

In [ ]:
import pandas as pd

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
(train_data, train_labels), (test_data, test_labels) = tf.keras.datasets.boston_housing.load_data()

In [ ]:
train_data[0]

In [ ]:
train_data.strides

In [ ]:
train_data.ndim

In [ ]:
train_data[1]

In [ ]:
train_labels.shape

In [ ]:
test_labels.shape

In [ ]:
test_data.shape

In [ ]:
train_data.dtype

In [ ]:
train_labels.dtype

In [ ]:
train_data.min(axis=0)

In [ ]:
train_data.max()

In [ ]:
train_data.max(axis=0)

In [ ]:
train_labels.max()

In [ ]:
# Normalize between 0, 1
# Data type to float32
# Shape compatibality

In [ ]:
min_max_scaler = MinMaxScaler()

In [ ]:
min_max_scaler.fit(train_data)

In [ ]:
train_data = min_max_scaler.transform(train_data)

In [ ]:
train_data.max(axis=0)

In [ ]:
train_data.min(axis=0)

In [ ]:
train_data[0]

In [ ]:
test_data = min_max_scaler.transform(test_data)

In [ ]:
test_data.min(axis=0)

In [ ]:
test_data.max(axis=0)

In [ ]:
train_data = train_data.astype(np.float32)

In [ ]:
train_data.dtype

In [ ]:
test_data = test_data.astype(np.float32)

In [ ]:
test_data.dtype

In [ ]:
train_labels.min()

In [ ]:
train_labels.max()

In [ ]:
train_labels.min(axis=0)

In [ ]:
train_labels.max(axis=0)

In [ ]:
train_labels = train_labels.astype(np.float32).reshape((-1, 1)) / 50.

In [ ]:
train_labels.min()

In [ ]:
train_labels.min(axis=0)

In [ ]:
train_labels.max()

In [ ]:
train_labels.max(axis=0)

In [ ]:
train_labels.dtype

In [ ]:
train_labels.shape

In [ ]:
test_labels = test_labels.astype(np.float32).reshape((-1, 1)) / 50.

In [ ]:
test_labels.shape

In [ ]:
test_labels.dtype

In [ ]:
test_labels.max()

In [ ]:
test_labels.min()

In [ ]:
train_labels.min()

In [ ]:
train_data.shape, train_data.dtype, train_data.min(), train_data.max()

In [ ]:
test_data.shape, test_data.dtype, train_data.min(), test_data.max()

In [ ]:
test_labels.shape, test_labels.dtype, test_labels.min(), test_labels.max()

In [ ]:
train_labels.shape, train_labels.dtype, train_labels.min(), train_labels.max()

In [ ]:
from tensorflow.keras.models import Model, Sequential

In [ ]:
from tensorflow.keras.layers import Input, Dense

In [ ]:
seq_model = Sequential()

In [ ]:
input_layer = Input((13, ), )

In [ ]:
first_layer_output = Dense(units=13, activation=tf.nn.relu, use_bias=False)(input_layer)

In [ ]:
second_layer_output = Dense(units=8, activation=tf.nn.relu, use_bias=False)(first_layer_output)

In [ ]:
predictions = Dense(units=1)(second_layer_output)

In [ ]:
regression_model = Model(input_layer, predictions)

In [ ]:
regression_model.summary()